# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta')], default=2),
        ),
    ]
