# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='observacion',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
