# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
    ]
