# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='observacion',
            new_name='descripcion',
        ),
    ]
