# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento', '0005_auto_20180325_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='prioridad',
        ),
    ]
