# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_trabajador', models.IntegerField(choices=[(1, 'Contrato Tiempo Determinado'), (2, 'Contrato Tiempo Indeterminado')], default=1)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('analista', models.BooleanField(default='false')),
                ('extension', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default='true')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.cargo')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.region')),
            ],
        ),
    ]
