# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='tipo_trabajador',
            field=models.IntegerField(choices=[(1, 'Contrato Tiempo Determinado'), (2, 'Contrato Tiempo Indeterminado')], default=2),
        ),
        migrations.DeleteModel(
            name='tipo',
        ),
    ]
