# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='analista',
            field=models.BooleanField(),
        ),
    ]
