# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180325_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='observacion',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
